# Generated by Django 2.2 on 2020-05-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
    ]
