# Generated by Django 2.2 on 2020-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes1', '0002_remove_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='заметка', max_length=120),
        ),
    ]
